import pygame

#Game size
COLUMNS = 10
ROWS = 20
CELL_SIZE = 40
GAME_WIDTH, GAME_HEIGHT = COLUMNS * CELL_SIZE, ROWS * CELL_SIZE

# side bar size
SIDEBAR_WIDTH = 200
PREVIEW_HEIGHT_FRACTION = 70
SCORE_HEIGHT_FRACTION = 1 - PREVIEW_HEIGHT_FRACTION

#window
PADDING = 20
WINDOW_WIDTH = GAME_WIDTH + SIDEBAR_WIDTH + PADDING * 3
WINDOW_HEIGHT = GAME_HEIGHT + PADDING * 2

#game behavior
# UPDATE_START_SPEED = 800
# MOVE_WAIT_TIME = 200
# ROTATE_WAIT_TIME = 200
# BLOCK_OFFSET =  pygame.Vector2(COLUMNS // 2, -1)

#color
GREEN = '#edffed'